REGISTRATION_SUCCESS = "User registered successfully."
PROFILE_UPDATE_SUCCESS = "Profile updated successfully."
DELETE_USER_EXISTING_BOOKINGS = "Cannot delete the object. User has existing bookings."
DELETE_USER_PROFILE_SUCCESS = "Profile deleted successfully."
PASSWORD_RESET_LINK_SENT = "Password reset link sent."
PASSWORD_RESET_SUCCESS = "Password successfully reset."

UPDATE_SUCCESS = "Updated successfully."
DELETE_SUCCESS = "Deleted successfully."
DELETE_TYPE_EXISTING_BOOKINGS = "Cannot delete the object. This type has existing bookings."
DELETE_BRAND_EXISTING_BOOKINGS = "Cannot delete the object. This brand has existing bookings."
DELETE_CAR_EXISTING_BOOKINGS = "Cannot delete the object. This Car has existing bookings."
INVALID_START_END_DATE = "Invalid request, start date should be before the end date."
INVALID_START_DATE = "Invalid request, start date should be today or later."

CAR_BOOKING_NOT_AVAILABLE = "Car booking not available for given dates."
ORDER_ALREADY_CANCELLED = "Invalid request, order is already canceled."
ORDER_CANCEL_FAILED = "Sorry the cancel request could not be processed."
LATE_ORDER_CANCEL = "Order cannot be canceled after the booking date."
ORDER_CANCEL_SUCCESS = "Order canceled successfully."
INVALID_REQUEST = "Invalid request."
CAR_RETURN_SUCCESS = "Car return successfully."
PROVIDE_START_END_DATE = "Start date and End date are mandatory."