# Generated by Django 4.0.5 on 2022-06-08 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_admin_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid phone number. Only 10 digits allowed.', regex='^d{10}$')]),
        ),
    ]
