# Generated by Django 4.0.5 on 2022-06-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seats', models.IntegerField(default=4)),
                ('fuel_type', models.IntegerField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Gas'), (4, 'Electric')], default=1)),
                ('transmission_type', models.IntegerField(choices=[(1, 'Manual'), (2, 'Automatic')], default=1)),
                ('reg_number', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.type')),
            ],
        ),
    ]
