# Generated by Django 4.0.5 on 2022-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('gas', 'gas'), ('electric', 'electric')], default=1, max_length=10),
        ),
    ]
