# Generated by Django 4.0.5 on 2022-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], default=1, max_length=10),
        ),
    ]
