# Generated by Django 4.0.5 on 2022-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='type',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
