# Generated by Django 4.0.5 on 2022-06-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_brand_available_type_available_alter_car_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
