# Generated by Django 4.0.5 on 2022-06-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
