# Generated by Django 4.0.5 on 2022-06-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_fuel_type'),
        ('orders', '0002_rename_end_time_order_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_set', to='cars.car'),
        ),
    ]
