# Generated by Django 4.0.5 on 2022-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
