# Generated by Django 4.0.5 on 2022-06-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, default='2022-06-23'),
            preserve_default=False,
        ),
    ]
