# Generated by Django 4.0.5 on 2022-07-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='canceled',
            new_name='cancelled',
        ),
    ]
