# Generated by Django 4.0.5 on 2022-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_canceled_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fine_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='fine_payment_intent_id',
            field=models.CharField(max_length=100, unique=True, null=True, blank=True),
            preserve_default=False,
        ),
    ]
